version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install:
          node-version: "16.17.1"
      - checkout
      - run:
          name: Install packages
          command: |
            npm install
      - run:
          name: Install packages
          command: |
            npm run build
  deploy:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install:
          node-version: "16.17.1"
      - checkout
      # - run:
      #     name: Configure git
      #     command: |
      #       git config user.email "circleci@circleci.com" && git config user.name "circleci"
      - run:
          name: Install packages
          command: |
            npm install
      - run:
          name: Install packages
          command: |
            npm run build
      - run:
          name: Deploy
          command: |
            npm install && npm run deploy
workflows:
  build and deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
